# -*- coding: utf-8 -*-
"""Copy of uciml final .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tjIci0GBlFQldzN5VOx3pPPFYM0Pnz6
"""

# ==========================================
# 1. IMPORT LIBRARIES main
# ==========================================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD

import shap


# ==========================================
# 2. LOAD DATA
# ==========================================
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

cols = ["age","sex","cp","trestbps","chol","fbs","restecg",
        "thalach","exang","oldpeak","slope","ca","thal","target"]

df = pd.read_csv(url, names=cols)

df.replace("?", np.nan, inplace=True)
df = df.dropna()
df = df.astype(float)


# ==========================================
# 3. FEATURE ENGINEERING (ONLY THIS)
# ==========================================
df['disease_score'] = df['cp'] + df['exang'] + df['oldpeak'] + df['ca']
df['target'] = df['target'].apply(lambda x: 1 if x > 0 else 0)


# ==========================================
# 4. ENCODING
# ==========================================
df = pd.get_dummies(df, columns=['cp','thal','slope'], drop_first=True)

X = df.drop('target', axis=1)
y = df['target']


# ==========================================
# 5. TRAIN TEST SPLIT
# ==========================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# ==========================================
# 6. SCALING
# ==========================================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# ==========================================
# 7. RANDOM FOREST
# ==========================================
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_scaled, y_train)

y_pred = rf.predict(X_test_scaled)
y_pred_prob = rf.predict_proba(X_test_scaled)[:,1]

print("\n📊 MODEL PERFORMANCE:")
print("AUC:", roc_auc_score(y_test, y_pred_prob))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))


# ==========================================
# 8. CONTENT-BASED (COSINE)
# ==========================================
content_sim = cosine_similarity(X_train_scaled)

def content_rec(idx, k=5):
    return content_sim[idx].argsort()[-k-1:-1][::-1]


# ==========================================
# 9. COLLABORATIVE (SVD)
# ==========================================
svd = TruncatedSVD(n_components=5, random_state=42)
latent = svd.fit_transform(X_train_scaled)

collab_sim = cosine_similarity(latent)

def collab_rec(idx, k=5):
    return collab_sim[idx].argsort()[-k-1:-1][::-1]


# ==========================================
# 10. HYBRID (0.5 + 0.5)
# ==========================================
def hybrid_rec(idx, k=5):
    score = 0.5 * content_sim[idx] + 0.5 * collab_sim[idx]
    return score.argsort()[-k-1:-1][::-1]



# ==========================================
# 11. ML FILTER (HEALTHY)
# ==========================================
def ml_rec(idx, k=5):
    candidates = hybrid_rec(idx, k=20)
    return [i for i in candidates if y_train.iloc[i] == 0][:k]


# ==========================================
# 12. PATTERN LEARNING
# ==========================================
def get_pattern(idx):
    return X_train.iloc[ml_rec(idx)].mean()


# ==========================================
# 13. FEATURE → ACTION MAP (ML REPRESENTATION)
# ==========================================
action_map = {
    "trestbps": ["Reduce Salt Intake", "Cardio Exercise", "Stress Reduction"],
    "chol": ["Balanced Diet", "Increase Fiber Intake", "Reduce Fat Intake"],
    "thalach": ["Increase Physical Activity", "Aerobic Exercise"],
    "oldpeak": ["Stress Management", "Yoga"],
    "disease_score": ["Overall Lifestyle Improvement"]
}


# ==========================================
# 14. EXPLAINABLE RECOMMENDATION (WHY + WHAT)
# ==========================================
def explain_lifestyle(idx):

    patient = X_train.iloc[idx]
    pattern = get_pattern(idx)

    diff = (pattern - patient).sort_values(key=abs, ascending=False)

    print("\n🔥 Personalized Recommendations with Reasons:\n")

    count = 0

    for f in diff.index:

        if f in action_map:

            status = "LOW" if diff[f] > 0 else "HIGH"

            print(f"👉 {f} is {status} compared to healthy patients")

            for act in action_map[f]:
                print("   •", act)

            count += 1

        if count == 3:
            break


# ==========================================
# 15. SHAP (XAI)
# ==========================================
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_train_scaled)

# For binary classification with RandomForestClassifier, shap_values is typically a list of arrays
# or a 3D array (n_samples, n_features, n_outputs). We want the SHAP values for the positive class (index 1).

# If shap_values is a list of two 2D arrays (one per class):
if isinstance(shap_values, list):
    shap_vals_for_positive_class = shap_values[1] # SHAP values for the positive class
# If shap_values is a single 3D array (n_samples, n_features, n_outputs):
else:
    shap_vals_for_positive_class = shap_values[:, :, 1] # SHAP values for the positive class

importance = np.abs(shap_vals_for_positive_class).mean(axis=0)

imp_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

print("\n🔍 Top Important Features (SHAP):")
print(imp_df.head(10))
# SHAP Graph
print("\n📊 SHAP Summary Plot:")
shap.summary_plot(shap_values, X_train_scaled)


# ==========================================
# 16. RISK SCORE + RANKING
# ==========================================
X_scaled_full = scaler.transform(X)

df['Risk_Score'] = rf.predict_proba(X_scaled_full)[:,1]

df['Risk_Rank'] = df['Risk_Score'].rank(ascending=False, method='dense')


# ==========================================
# 17. FEEDBACK
# ==========================================
df['AI_Feedback'] = pd.cut(
    df['Risk_Score'],
    bins=[0, 0.2, 0.4, 0.6, 0.8, 1],
    labels=[
        "Healthy – Keep it up",
        "Low Risk – Maintain Lifestyle",
        "Moderate Risk – Improve Habits",
        "High Risk – Medical Attention",
        "Critical Risk – Immediate Action"
    ],
    include_lowest=True
)


# ==========================================
# 18. FINAL OUTPUT
# ==========================================
print("\n🔥 TOP 10 HIGH-RISK PATIENTS:\n")

print(df.sort_values(by='Risk_Score', ascending=False)[[
    'Risk_Score','Risk_Rank','AI_Feedback'
]].head(10))


# ==========================================
# 19. TEST FOR ONE PATIENT
# ==========================================
idx = 67

print("\n🔹 Content:", content_rec(idx))
print("\n🔹 Collaborative:", collab_rec(idx))
print("\n🔹 Hybrid:", hybrid_rec(idx))
print("\n🔹 Healthy Similar:", ml_rec(idx))

# 👉 FINAL EXPLANATION
explain_lifestyle(idx)



# ==========================================
# TAKE INPUT FROM NEW USER
# ==========================================

print("\n===================================")
print("🩺 ENTER NEW USER DETAILS")
print("===================================")

age = int(input("Enter Age: "))
sex = int(input("Enter Sex (1=Male, 0=Female): "))
cp = int(input("Enter Chest Pain Type (1-4): "))
trestbps = float(input("Enter Resting Blood Pressure: "))
chol = float(input("Enter Cholesterol: "))
fbs = int(input("Enter Fasting Blood Sugar >120 (1=True,0=False): "))
restecg = int(input("Enter Rest ECG (0-2): "))
thalach = float(input("Enter Maximum Heart Rate: "))
exang = int(input("Enter Exercise Induced Angina (1=Yes,0=No): "))
oldpeak = float(input("Enter Oldpeak: "))
slope = int(input("Enter Slope (1-3): "))
ca = int(input("Enter Number of Major Vessels (0-3): "))
thal = int(input("Enter Thal (3,6,7): "))


# ==========================================
# CREATE NEW USER DATAFRAME
# ==========================================

new_user = {

    "age": age,
    "sex": sex,
    "cp": cp,
    "trestbps": trestbps,
    "chol": chol,
    "fbs": fbs,
    "restecg": restecg,
    "thalach": thalach,
    "exang": exang,
    "oldpeak": oldpeak,
    "slope": slope,
    "ca": ca,
    "thal": thal
}

user_df = pd.DataFrame([new_user])


# ==========================================
# FEATURE ENGINEERING
# ==========================================

user_df['disease_score'] = (

    user_df['cp']
    +
    user_df['exang']
    +
    user_df['oldpeak']
    +
    user_df['ca']
)


# ==========================================
# ENCODING
# ==========================================

user_df = pd.get_dummies(user_df)

user_df = user_df.reindex(
    columns=X.columns,
    fill_value=0
)


# ==========================================
# SCALING
# ==========================================

user_scaled = scaler.transform(user_df)


# ==========================================
# PREDICTION
# ==========================================

prediction = rf.predict(user_scaled)[0]

risk_score = rf.predict_proba(user_scaled)[0][1]


# ==========================================
# PATTERN LEARNING
# ==========================================

content_scores = cosine_similarity(
    user_scaled,
    X_train_scaled
)[0]

content_users = content_scores.argsort()[-6:-1][::-1]

user_latent = svd.transform(user_scaled)

collab_scores = cosine_similarity(
    user_latent,
    latent
)[0]

hybrid_scores = (
    0.5 * content_scores
    +
    0.5 * collab_scores
)

hybrid_users = hybrid_scores.argsort()[-6:-1][::-1]

healthy_users = [

    i for i in hybrid_users

    if y_train.iloc[i] == 0
]

if len(healthy_users) == 0:

    healthy_users = hybrid_users[:5]

healthy_pattern = X_train.iloc[
    healthy_users
].mean()

diff = (
    healthy_pattern
    -
    user_df.iloc[0]
).sort_values(
    key=abs,
    ascending=False
)


# ==========================================
# FINAL REPORT
# ==========================================

print("\n===================================")
print("🩺 HEART HEALTH REPORT")
print("===================================")

print("\n📊 Risk Score:", round(risk_score, 3))


# ==========================================
# HEALTHY CONDITION
# ==========================================

if risk_score < 0.2:

    print("\n✅ Your heart health condition looks healthy.\n")

    print("💚 Health Maintenance Tips:\n")

    print("• Continue eating a balanced diet rich in fruits and vegetables.")

    print("• Maintain regular physical activity and proper sleep.")

    print("• Drink enough water and avoid excessive junk food.")

    print("• Continue stress management and regular health checkups.")

    print("• Avoid smoking, alcohol, and unhealthy lifestyle habits.")


# ==========================================
# LOW / MODERATE RISK CONDITION
# ==========================================

elif risk_score < 0.6:

    print("\n⚠ Your heart health requires lifestyle improvements.\n")

    count = 0

    for f in diff.index:

        if f in action_map:

            status = "LOW" if diff[f] > 0 else "HIGH"

            print(f"\n👉 {f} is {status}")

            for act in action_map[f]:

                print("   •", act)

            count += 1

        if count == 3:
            break


# ==========================================
# HIGH / CRITICAL RISK CONDITION
# ==========================================

else:

    print("\n🚨 High heart disease risk detected.\n")

    print("⚠ Immediate lifestyle and medical attention is recommended.\n")

    count = 0

    for f in diff.index:

        if f in action_map:

            status = "LOW" if diff[f] > 0 else "HIGH"

            print(f"\n👉 Critical Factor: {f} is {status}")

            for act in action_map[f]:

                print("   •", act)

            count += 1

        if count == 4:
            break

    print("\n🏥 Additional Medical Advice:")

    print("• Schedule a full heart health checkup immediately.")

    print("• Monitor blood pressure, cholesterol, and blood sugar regularly.")

    print("• Follow a strict low-fat and low-salt diet.")

    print("• Avoid smoking, alcohol, and stress.")

    print("• Consult a cardiologist for professional medical guidance.")